user: idb
group: idb
vendor: bytemine GmbH
maintainer: info@bytemine.net
homepage: https://www.bytemine.net/
before: 
    - ln -s config-example config
    - ./scripts/mark-version.sh
targets:
  ubuntu-20.04:
    build_dependencies:
      - libgmp-dev
      - build-essential
      - bison
      - openssl
      - libreadline8
      - libreadline-dev
      - curl
      - git-core
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libxml2-dev
      - autoconf
      - libc6-dev
      - libncurses-dev
      - automake
      - libtool
      - libmysqlclient-dev
      - mysql-client
      - libxslt1.1
      - libxslt1-dev
    dependencies:
      - apache2
      - mariadb-server
      - redis-server
      - vim
      - postfix
      - libapache2-mod-passenger
    after_install: "scripts/debian/postinst.sh"
